# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_best_split_cox_bone <- function(time, event, xx_numeric, xx_factor, weights, min_weights = 50.0) {
    .Call(`_SurvivalClusteringTree_find_best_split_cox_bone`, time, event, xx_numeric, xx_factor, weights, min_weights)
}

